/*
 * This file is generated by jOOQ.
 */
package com.jooq.generator.tables.daos;


import com.jooq.generator.tables.Fruit;
import com.jooq.generator.tables.records.FruitRecord;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class FruitDao extends DAOImpl<FruitRecord, com.jooq.generator.tables.pojos.Fruit, Long> {

    /**
     * Create a new FruitDao without any configuration
     */
    public FruitDao() {
        super(Fruit.FRUIT, com.jooq.generator.tables.pojos.Fruit.class);
    }

    /**
     * Create a new FruitDao with an attached configuration
     */
    @Autowired
    public FruitDao(Configuration configuration) {
        super(Fruit.FRUIT, com.jooq.generator.tables.pojos.Fruit.class, configuration);
    }

    @Override
    public Long getId(com.jooq.generator.tables.pojos.Fruit object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Fruit.FRUIT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchById(Long... values) {
        return fetch(Fruit.FRUIT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.jooq.generator.tables.pojos.Fruit fetchOneById(Long value) {
        return fetchOne(Fruit.FRUIT.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Fruit.FRUIT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchByName(String... values) {
        return fetch(Fruit.FRUIT.NAME, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchRangeOfPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(Fruit.FRUIT.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.jooq.generator.tables.pojos.Fruit> fetchByPrice(BigDecimal... values) {
        return fetch(Fruit.FRUIT.PRICE, values);
    }
}
