/*
 * This file is generated by jOOQ.
 */
package com.jooq.generator;


import com.jooq.generator.tables.Book;
import com.jooq.generator.tables.Fruit;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqTest extends SchemaImpl {

    private static final long serialVersionUID = 273582912;

    /**
     * The reference instance of <code>jooq-test</code>
     */
    public static final JooqTest JOOQ_TEST = new JooqTest();

    /**
     * The table <code>jooq-test.book</code>.
     */
    public final Book BOOK = com.jooq.generator.tables.Book.BOOK;

    /**
     * The table <code>jooq-test.fruit</code>.
     */
    public final Fruit FRUIT = com.jooq.generator.tables.Fruit.FRUIT;

    /**
     * No further instances allowed
     */
    private JooqTest() {
        super("jooq-test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Book.BOOK,
            Fruit.FRUIT);
    }
}
