/*
 * This file is generated by jOOQ.
 */
package com.jooq.generator;


import com.jooq.generator.tables.Book;
import com.jooq.generator.tables.Fruit;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq-test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq-test.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq-test.fruit</code>.
     */
    public static final Fruit FRUIT = Fruit.FRUIT;
}
